version: '3.1'
services:
  rabbitmq:
    container_name: springboot2-rabbitmq
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: example
      RABBITMQ_DEFAULT_VHOST: springboot2-rabbitmq
      RABBITMQ_LOGS: /var/lib/rabbitmq/rabbitmq.log
      RABBITMQ_SASL_LOGS: /var/lib/rabbitmq/rabbitmq-sasl.log
#    volumes:
#      - "./target/data/rabbitmq:/var/lib/rabbitmq"
