version: "3.8"
services:
  springboot2-docker:
    image: shijian/springboot2-docker:latest
    container_name: springboot2-docker # can ping by container name; default is folder+image name
    hostname: springboot2-docker # can ping by hostname; default is random value
    # internal for "springboot2-docker-client" only
#    ports:
#      - "8080:8080"
    networks:
      - springboot2-docker-network
    # for swarm mode
#    deploy:
#      replicas: 1
#      update_config:
#        parallelism: 2
#        delay: 10s
#      restart_policy:
#        condition: on-failure

  springboot2-docker-client:
    image: shijian/springboot2-docker-client:latest
    container_name: springboot2-docker-client
    hostname: springboot2-docker-client
    ports:
      - "8081:8081"
    networks:
      - springboot2-docker-network
    # depends_on only check it until "running", not "ready"
    # https://docs.docker.com/compose/startup-order/
    depends_on:
      - springboot2-docker
    # for swarm mode
#    deploy:
#      replicas: 1
#      update_config:
#        parallelism: 2
#        delay: 10s
#      restart_policy:
#        condition: on-failure

networks:
  springboot2-docker-network:
    name: springboot2-docker-network
